server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # Do not cache index.html
  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }

  # Cache static assets for a long time
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
